{% set setupdata = load_setup_py_data() %}

package:
  name: diffpy.pdffit2
  version: {{ setupdata['version'] }}

source:
  # git_url: https://github.com/diffpy/diffpy.pdffit2.git
  git_url: ..

build:
  preserve_egg_dir: True

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}     # [py3k or not win]
    - gsl {{ gsl }}
  host:
    - python {{ python }}
    - pip
    - setuptools

  run:
    - python
    - setuptools
    - six
    - diffpy.structure >=3

test:
  # Python imports
  imports:
    - diffpy
    - diffpy.pdffit2
    - diffpy.pdffit2.ipy_ext
    - diffpy.pdffit2.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/diffpy/diffpy.pdffit2
  summary: PDFfit2 - real space structure refinement program
  license: Modified BSD License
  license_file: LICENSE.txt

# See http://docs.continuum.io/conda/build.html
# for more information about meta.yaml.
