name: Check News Item
on:
  pull_request_target:
    branches:
    - main
jobs:
  build:
    uses: Billingegroup/release-scripts/.github/workflows/_check-news-item.yml@main
    with:
      project: diffpy.pdffit2
