name: CI

on:
  push:
    branches:
      - main
  release:
    types:
      - prereleased
      - published
  workflow_dispatch: null

jobs:
  coverage:
    uses: Billingegroup/release-scripts/.github/workflows/_matrix-and-codecov-on-merge-to-main.yml@v0
    with:
      project: diffpy.pdffit2
      c_extension: false
      headless: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
