name: Tests build sdist

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_sdist:
    name: Build diffpy.pdffit2 sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: ./dist/*.tar.gz
